In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm import tqdm

import warnings
warnings.filterwarnings("ignore")

In [76]:
data = pd.read_csv(r'D:\NationalSecret\IE105\data\all_ver2.csv')
data

Payload  Label
0       id=2&nombre=Vino+Rioja&precio=39&cantidad=72&...      0
1      <login><username>john_doe</username><password>...      0
2       modo=registro&login=aronstam&password=373406N...      0
3      modo=entrar&login=delila&pwd=ipe$cacuana&remem...      0
4      <login><username>john_doe</username><password>...      0
...                                                  ...    ...
66011  modo=registro&login=kimbroug&password=3m6noja4...      0
66012          <tbody onpointermove=alert(1)>XSS</tbody>      1
66013  <order><item>Phone</item><price>500</price></o...      0
66014  <DIV STYLE="background-image: url(javascript:a...      1
66015  <style>:target {color: red;}</style><figure id...      1

[66016 rows x 2 columns]

In [78]:
data.Label.value_counts()

Label
0    27364
1    18196
2    14941
3     5000
4      515
Name: count, dtype: int64

In [81]:
data = data.dropna()
data

Payload  Label
0       id=2&nombre=Vino+Rioja&precio=39&cantidad=72&...      0
1      <login><username>john_doe</username><password>...      0
2       modo=registro&login=aronstam&password=373406N...      0
3      modo=entrar&login=delila&pwd=ipe$cacuana&remem...      0
4      <login><username>john_doe</username><password>...      0
...                                                  ...    ...
66011  modo=registro&login=kimbroug&password=3m6noja4...      0
66012          <tbody onpointermove=alert(1)>XSS</tbody>      1
66013  <order><item>Phone</item><price>500</price></o...      0
66014  <DIV STYLE="background-image: url(javascript:a...      1
66015  <style>:target {color: red;}</style><figure id...      1

[66015 rows x 2 columns]

In [82]:
X = data['Payload']
y = data['Label']

vectorizer = TfidfVectorizer()
X_tfidf = vectorizer.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=0.2, random_state=42)

In [83]:
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.971597364235401
Confusion Matrix:
 [[5148    0  358    0    2]
 [   0 3515    6    0    0]
 [   0    0 3021    0    0]
 [   0    0    0 1053    0]
 [   0    2    7    0   91]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.93      0.97      5508
           1       1.00      1.00      1.00      3521
           2       0.89      1.00      0.94      3021
           3       1.00      1.00      1.00      1053
           4       0.98      0.91      0.94       100

    accuracy                           0.97     13203
   macro avg       0.97      0.97      0.97     13203
weighted avg       0.97      0.97      0.97     13203



In [84]:
import joblib

joblib.dump(rf, 'rf_model_ver3.pkl')
joblib.dump(vectorizer, 'vectorizer_3.pkl')

['vectorizer_3.pkl']